### ISSUE TITLE
Packaging and versioning

### ISSUE THREAD

**Issue by adrienverge** [metricq/aiocouch#17]
First, thanks for this piece of software: it's smartly designed and provides a great async replacement for [couchdb-python](https://github.com/djc/couchdb-python).  Since you accepted my pull requests, my team and I can start using for real!

aiocouch is currently in version 0.0, and not available in packages repositories.

I propose to:
1. Release a first version.
   - I recommend following [semantic versioning](https://semver.org/).
   - Version 1.0.0 or 0.1.0? In my opinion, the lib is ready (it just lacks documentation :wink:). I'd be for 1.0.0 :+1:

2. Publish the package on PyPi, so users can install it using `pip`.  I haven't reserved the name `aiocouch` to let you the honor :wink: but if you want I can do it and push the first version and/or co-maintain the repo. I have been maintaining other PyPi packages for some years ([yamllint](https://pypi.org/project/yamllint/), [localstripe](https://pypi.org/project/localstripe/), [coucharchive](https://pypi.org/project/coucharchive/), [photocollage](https://pypi.org/project/photocollage/), ...)

   Do you want me to create the package `aiocouch` on PyPi and add you as *owner* (in this case, address tu-dresden or googlemail?)

   Or you prefer doing it yourself?

   Or maybe you already had other plans?

Thanks again,

Adrien

**Comment by bmario** [comment]
Thanks. I'll take care of it soon™. I want to look into issues, which popped up when I tried to test against CouchDB3 first.

Btw. a heads-up for you from the changelog:
>[#2339](https://github.com/apache/couchdb/pull/2339): All databases are now created by default as admin-only. That is, the default new database _security object is now:
>
>
```
{
  "members" : { "roles" : [ "_admin" ] },
   "admins" : { "roles" : [ "_admin" ] }
}
```
>
> This can be changed after database creation.

**Comment by adrienverge** [comment]
> Btw. a heads-up for you from the changelog:

Interesting!

**Comment by adrienverge** [comment]
Thanks! https://pypi.org/project/aiocouch/
