### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by adrienverge** [metricq/aiocouch#18]
CouchDB support attaching binary files to documents, using `/db/doc/attachment` path: https://docs.couchdb.org/en/2.3.0/api/document/attachments.html

Do you have any plans to implement that? If not, I propose to look into it. This could go in a new `aiocouch.attachment.Attachment` class, with a `Document().attachment(id)` helper.

**Comment by bmario** [comment]
It sounds like a good idea to me. I'll gladly accept a PR.

I also see an `aiocouch.remote.Attachment` class.
