### ISSUE TITLE
Document to dict

### ISSUE THREAD

**Issue by pepoluan** [metricq/aiocouch#38]
Is there an "official" way to convert a `Document` instance to a normal `dict`?

The reason is that we are only interested in reading & manipulating the data, and because `Document` implemented the `.copy()` method we got some surprise treating an instance of `Document` as a dict.

**Edit:** After perusing the source, it seems that `.data` provides access to the internal dict that underlies `Document`. Do I get this correctly? It's it safe to grab `.data` and treats it like a dict?

**Comment by bmario** [comment]
Hey,

yes, `data` should be what you're looking for. https://aiocouch.readthedocs.io/en/stable/document.html#aiocouch.document.Document.data

Be vary though, the documentation has some rough edges. In particular, `data` returns `None` if `fetch()` wasn't awaited, or the received data denoted a deleted document.
