### ISSUE TITLE
Race condition with couchdb.create exists_ok=True

### ISSUE THREAD

**Issue by starlord-daniel** [metricq/aiocouch#42]
In our project we found that if you are calling the `couchdb.create` method with `exists_ok` set to `True`, then it could happen, that you still get the following error:

```bash
raise exception_type(message.format(**message_input)) from exception
aiocouch.exception.PreconditionFailedError: Database already exists
```

This should not happen, as we are already ok with the database existing. 

I've will open a PR to address this and link it **HERE**
Please give feedback, if that solution follows the packages approach and works for you.

**Comment by bmario** [comment]
Thanks for the report and PR, I've worked on a solution including more tests in parallel though.
