### ISSUE TITLE
Expose sequence numbers

### ISSUE THREAD

**Issue by pepijndevos** [metricq/aiocouch#45]
I'm trying to use your quite lovely library, but unfortunately there is one huge problem, which is that there is no way to access the sequence number of a request, or the last sequence number of a changes feed.

This makes it basically impossible to fetch some documents, and then fetch the changes since that document was retrieved, and then the changes since you last requested the changes.

**Comment by bmario** [comment]
Hey, I'm not sure I completely understand, but you want to access the sequence return from events in the changes endpoint?

In that case, the events should give access to it. The documentation seems a bit odd, but ChangedEvent and DeletedEvent both inherit from BaseChangeEvent, which contains the [sequence](https://aiocouch.readthedocs.io/en/stable/database.html#aiocouch.event.BaseChangeEvent.sequence).

**Comment by pepijndevos** [comment]
When you pass `update_seq` to a view (or `_all_docs`) it will return the sequence that view was taken at, so you can request changes since then.

**Comment by bmario** [comment]
Looks like all existing methods in the `View` class are generators. How would you imagine an interface for that?

**Comment by bmario** [comment]
Have a look at #46. The `ViewResponse` class should be what you're looking for.

**Comment by pepijndevos** [comment]
Looks good!
